### ISSUE TITLE
I could use a little help please

### ISSUE THREAD

**Issue by staifokuzed** [sammy007/monero-stratum#14]
I am very much a noob when it comes to this sort of thing.    I have been struggling with this for a bit now and I have been able to solve most of my issues by research.  Now I am stuck though.  The steps below are what I exactly follow trying to get this up and running (well up to the point where I dont know what to do).   It is a VPS running Ubuntu 16.04 - 64-bit (Standard).

Change password
sudo passwd root	

	update
apt-get update 
apt-get dist-upgrade
sudo apt-get -y upgrade(IF ABORT AFTER YES)

	swap
dd if=/dev/zero of=/mnt/myswap.swap bs=1M count=4000
mkswap /mnt/myswap.swap
swapon /mnt/myswap.swap

sudo apt-get install nano

nano /etc/fstab

Add the following line at the end of the file.

/mnt/myswap.swap none swap sw 0 0
Ctrl+O to save, and Ctrl+X to exit the nano editor.

------------RESTART--------------

*******go-1.6********* SKIPPED THIS STEP IN LAST INSTALL*************
  (I tried a fresh install and just used used golang install at end)

sudo apt-get install curl

sudo curl -O https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz
sudo tar -xvf go1.6.linux-amd64.tar.gz

sudo mv go /usr/local

sudo nano ~/.profile

At the end of the file, add this line:

export PATH=$PATH:/usr/local/go/bin
  cntrl-o and cntrl-x
source ~/.profile
***************************************************************************

sudo apt install git

sudo apt install cmake

sudo apt install build-essential ********

******* GCC * only if ^^^^^^^ does not work correctly*********************

sudo apt-get install software-properties-common python-software-properties

sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update
sudo apt-get install gcc-snapshot -y
sudo apt-get update
sudo apt-get install gcc-6 g++-6 -y
sudo apt-get update
****************************************************************************

	Package
sudo apt-get install pkg-config

	Boost	1.58
apt-get install libboost-all-dev

	Openssllibssl-dev
sudo apt-get install libssl-dev

        libunbound	1.4.16
sudo apt-get install libunbound-dev

	libminiupnpc	2.0
sudo apt-get install libminiupnpc-dev

	libunwind
sudo apt-get install libunwind8-dev	

	liblzma
sudo apt-get install liblzma-dev

	ldns
sudo apt-get install libldns-dev

	expat	1.1
sudo apt-get install libexpat1-dev

	GTest
sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/

	Doxygen
sudo apt-get install doxygen

	Graphviz
sudo apt-get install graphviz

git clone https://github.com/monero-project/monero.git
cd monero
cmake -DBUILD_SHARED_LIBS=1
make

	Golang and packages

sudo apt-get install golang
export GOPATH=~/go
go get github.com/yvasiyarov/gorelic

	Build CGO extensions:

MONERO_DIR=/opt/src/monero cmake

 cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

**Comment by sammy007** [comment]
Sorry, this is beyond. Hire an admin.
