### ISSUE TITLE
#10

### ISSUE THREAD

**Issue by discipuloosho** [sammy007/monero-stratum#16]
I follow STRICTLY build steps, but when `$ go build -o pool main.go`:
```
hashing/libhashing.so: undefined reference to cn_slow_hash 
hashing/libhashing.so: undefined reference to cn_fast_hash
collect2: error: ld returned 1 exit status
```

**Comment by xstillwill** [comment]
git checkout v0.10.3 after cloning monero and all compiles just fine

**Comment by discipuloosho** [comment]
I check out, thanks :) @xstillwill

**Comment by discipuloosho** [comment]
SOLVED. Thanks so much, @xstillwill

**Comment by gnif** [comment]
The proper fix for this is to add cncrypto to hashing/CMakeLists.txt

`target_link_libraries(${LIB} crypto cncrypto)`
