### ISSUE TITLE
main.go

### ISSUE THREAD

**Issue by kexroman** [sammy007/monero-stratum#17]
Hi ,  may be smth wrong in install readme for linux - it can't find main.go
As I understand monero src has to be clone to /opt/src/monero? 
On what step it will generate main.go ?

[```
 97%] Built target cn_deserialize
[100%] Built target blockchain_export
roman@eel:/opt/monero$ go build -o pool main.go
stat main.go: no such file or directory
roman@eel:/opt/monero$ 

```

**Comment by xstillwill** [comment]
Thought about cloning the repo you are trying to compile? ?????

Von meinem iPhone gesendet

Am 04.06.2017 um 16:39 schrieb kexroman <notifications@github.com<mailto:notifications@github.com>>:


Hi , may be smth wrong in install readme for linux - it can't find main.go
As I understand monero src has to be clone to /opt/src/monero?
On what step it will generate main.go ?

[```
97%] Built target cn_deserialize
[100%] Built target blockchain_export
roman@eel:/opt/monero$ go build -o pool main.go
stat main.go: no such file or directory
roman@eel:/opt/monero$

-

**Comment by kexroman** [comment]
readme said : 
git clone https://github.com/monero-project/monero.git ( somewhere )...
Then it said to use directory /opt/src/monero - but I just to change it to  /opt/monero (see below last install step)
`roman@eel:/opt/monero$ MONERO_DIR=/opt/monero cmake .
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries with position independent code
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled
-- Could not find miniupnp
-- Using miniupnpc from local source tree (/external/miniupnpc)
-- Looking for libunbound
-- Using 64-bit LMDB from source tree
-- Building on x86_64 for native
-- AES support enabled
-- Found Boost Version: 105800
-- Found Git: /usr/bin/git
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/monero
roman@eel:/opt/monero$ make
[  0%] Built target version
[  7%] Built target libminiupnpc-static
[ 44%] Built target unbound
[ 45%] Built target lmdb
[ 46%] Built target easylogging
[ 55%] Built target obj_cncrypto
[ 55%] Built target cncrypto
[ 57%] Built target epee
[ 63%] Built target obj_common
[ 64%] Built target common
[ 66%] Built target obj_ringct
[ 69%] Built target obj_cryptonote_basic
[ 69%] Built target cryptonote_basic
[ 69%] Built target ringct
[ 71%] Built target obj_cryptonote_core
[ 73%] Built target blocks
[ 74%] Built target obj_blockchain_db
[ 74%] Built target blockchain_db
[ 75%] Built target cryptonote_core
[ 76%] Built target obj_mnemonics
[ 77%] Built target mnemonics
[ 78%] Built target obj_rpc
[ 79%] Built target obj_cryptonote_protocol
[ 80%] Built target obj_p2p
[ 81%] Built target p2p
[ 81%] Built target cryptonote_protocol
[ 82%] Built target rpc
[ 87%] Built target obj_wallet
[ 88%] Built target wallet
[ 89%] Built target wallet_rpc_server
[ 90%] Built target simplewallet
[ 90%] Built target obj_daemonizer
[ 90%] Built target daemonizer
[ 94%] Built target daemon
[ 96%] Built target blockchain_import
[ 97%] Built target cn_deserialize
[100%] Built target blockchain_export
roman@eel:/opt/monero$ go build -o pool main.go
stat main.go: no such file or directory
roman@eel:/opt/monero$`

**Comment by xstillwill** [comment]
Once again... did you clone the monero-stratum repo you are trying to compile ???

Von meinem iPhone gesendet

Am 04.06.2017 um 16:51 schrieb kexroman <notifications@github.com<mailto:notifications@github.com>>:


readme said :
git clone https://github.com/monero-project/monero.git ( somewhere )...
Then it said to use directory /opt/src/monero - but I just to change it to /opt/monero (see below last install step)
roman@eel:/opt/monero$ MONERO_DIR=/opt/monero cmake . -- Building without build tag -- Could not find DEVELOPER_LOCAL_TOOLS in env (not required) -- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF -- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required) -- Building for a 64-bit system -- Building internal libraries with position independent code -- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb) -- Using LMDB as default DB type -- Stack trace on exception enabled -- Could not find miniupnp -- Using miniupnpc from local source tree (/external/miniupnpc) -- Looking for libunbound -- Using 64-bit LMDB from source tree -- Building on x86_64 for native -- AES support enabled -- Found Boost Version: 105800 -- Found Git: /usr/bin/git -- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") -- Configuring done -- Generating done -- Build files have been written to: /opt/monero roman@eel:/opt/monero$ make [ 0%] Built target version [ 7%] Built target libminiupnpc-static [ 44%] Built target unbound [ 45%] Built target lmdb [ 46%] Built target easylogging [ 55%] Built target obj_cncrypto [ 55%] Built target cncrypto [ 57%] Built target epee [ 63%] Built target obj_common [ 64%] Built target common [ 66%] Built target obj_ringct [ 69%] Built target obj_cryptonote_basic [ 69%] Built target cryptonote_basic [ 69%] Built target ringct [ 71%] Built target obj_cryptonote_core [ 73%] Built target blocks [ 74%] Built target obj_blockchain_db [ 74%] Built target blockchain_db [ 75%] Built target cryptonote_core [ 76%] Built target obj_mnemonics [ 77%] Built target mnemonics [ 78%] Built target obj_rpc [ 79%] Built target obj_cryptonote_protocol [ 80%] Built target obj_p2p [ 81%] Built target p2p [ 81%] Built target cryptonote_protocol [ 82%] Built target rpc [ 87%] Built target obj_wallet [ 88%] Built target wallet [ 89%] Built target wallet_rpc_server [ 90%] Built target simplewallet [ 90%] Built target obj_daemonizer [ 90%] Built target daemonizer [ 94%] Built target daemon [ 96%] Built target blockchain_import [ 97%] Built target cn_deserialize [100%] Built target blockchain_export roman@eel:/opt/monero$ go build -o pool main.go stat main.go: no such file or directory roman@eel:/opt/monero$

-

**Comment by kexroman** [comment]
My fault. Sorry - I forgot to clone it. :)
But anyway - it should mentioned as step 0 .
Now I cloned it but it failed to compile 'cos of packages - how to add it in GO?

roman@eel:/opt/monero-stratum$ go build -o pool main.go
main.go:16:2: cannot find package "github.com/goji/httpauth" in any of:
	/usr/lib/go-1.6/src/github.com/goji/httpauth (from $GOROOT)
	/home/roman/go/src/github.com/goji/httpauth (from $GOPATH)
main.go:17:2: cannot find package "github.com/gorilla/mux" in any of:
	/usr/lib/go-1.6/src/github.com/gorilla/mux (from $GOROOT)
	/home/roman/go/src/github.com/gorilla/mux (from $GOPATH)
roman@eel:/opt/monero-stratum$roman@eel:/opt/monero-stratum$ ls -l /home/roman/go/src/github.com/yvasiyarov/
total 12
drwxrwxr-x 7 roman roman 4096 Jun  4 16:15 go-metrics
drwxrwxr-x 4 roman roman 4096 Jun  4 16:15 gorelic
drwxrwxr-x 4 roman roman 4096 Jun  4 16:15 newrelic_platform_go
roman@eel:/opt/monero-stratum$

Thanks for help!

**Comment by kexroman** [comment]
Ok, after add  needed  source from github to ~/go 
and it shows compilation error :
roman@eel:/opt/monero-stratum$ go build -o pool main.go
# _/opt/monero-stratum/hashing
hashing/libhashing.so: undefined reference to `cn_slow_hash'
hashing/libhashing.so: undefined reference to `cn_fast_hash'
collect2: error: ld returned 1 exit status
roman@eel:/opt/monero-stratum$

Could It be version error (i got the latest)?
People already report such issue in #10 issue - but w/o solution.

**Comment by xstillwill** [comment]
https://github.com/sammy007/monero-stratum/issues/16

**Comment by kexroman** [comment]
yep,fixed
xstillwill thanks!
