### ISSUE TITLE
/usr/bin/ld: cannot find -lcnutil

### ISSUE THREAD

**Issue by inhash** [sammy007/monero-stratum#19]
any idea how to fix this? I'm trying to build main.go  

```
cd $GOPATH/src/github.com/sammy007/monero-stratum
go build
# github.com/sammy007/monero-stratum/cnutil
/usr/bin/ld: cannot find -lcnutil
```

**Comment by sammy007** [comment]
Because layout of repo is not usual you don't have to use `go get`. Follow readme, you must clone repo.

**Comment by cascadiacrypto** [comment]
Hi sammy,

I'm having the same problem even though I followed the README.md 100% 

Could you perhaps better detail any step between cloning the repo and building the pool?

I'm stuck here:

commandctr@CommandCTR:~/monero$ git clone https://github.com/sammy007/monero-stratum.git
Cloning into 'monero-stratum'...
remote: Counting objects: 546, done.
remote: Total 546 (delta 0), reused 0 (delta 0), pack-reused 546
Receiving objects: 100% (546/546), 104.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (347/347), done.
Checking connectivity... done.
commandctr@CommandCTR:~/monero$ cd monero-stratum
commandctr@CommandCTR:~/monero/monero-stratum$ MONERO_DIR=/opt/src/monero cmake .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Using Monero source from env /opt/src/monero
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   program_options
--   date_time
--   filesystem
--   chrono
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/commandctr/monero/monero-stratum
commandctr@CommandCTR:~/monero/monero-stratum$ make
Scanning dependencies of target hashing
[ 25%] Building C object hashing/CMakeFiles/hashing.dir/src/hashing.c.o
/home/commandctr/monero/monero-stratum/hashing/src/hashing.c:1:29: fatal error: crypto/hash-ops.h: No such file or directory
compilation terminated.
hashing/CMakeFiles/hashing.dir/build.make:62: recipe for target 'hashing/CMakeFiles/hashing.dir/src/hashing.c.o' failed
make[2]: *** [hashing/CMakeFiles/hashing.dir/src/hashing.c.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'hashing/CMakeFiles/hashing.dir/all' failed
make[1]: *** [hashing/CMakeFiles/hashing.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
commandctr@CommandCTR:~/monero/monero-stratum$

**Comment by sammy007** [comment]
Updated readme.
