### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by sp1k31973** [sammy007/monero-stratum#21]
Hello 

I am new in solo minig and have a problem I have so around the 50kh
But after 24 hours comes no payout many Accepted shares but no block
is that normal?
My system runs on ubuntu 16.4 and 6 core, 8 gig ram, is monero starts without errors and your proxy pool al compiled without errors and starts without errors

https://www.pic-upload.de/view-33373855/IMG-20170620-WA0003.jpg.html

Thank you for any help

**Comment by sammy007** [comment]
There are no payouts, blockchain pays you if block found. Your shares worth nothing, you have to find block eventually. If you have no clue what you are doing please switch to public pool.
