### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by armpdq** [sammy007/monero-stratum#23]
Hello guys!
after 'cmake .' all  fine. but when i run 'make' command - i got this:
root@dev:/home/monero-stratum# make
Scanning dependencies of target hashing
[ 25%] Building C object hashing/CMakeFiles/hashing.dir/src/hashing.c.o
[ 50%] Linking C shared library libhashing.so
[ 50%] Built target hashing
Scanning dependencies of target cnutil
[ 75%] Building CXX object cnutil/CMakeFiles/cnutil.dir/src/cnutil.cpp.o
[100%] Linking CXX shared library libcnutil.so
/usr/bin/ld: cannot find -lcryptonote_core
/usr/bin/ld: cannot find -lcryptonote_basic
/usr/bin/ld: cannot find -lcommon
/usr/bin/ld: cannot find -lringct
collect2: error: ld returned 1 exit status
cnutil/CMakeFiles/cnutil.dir/build.make:99: recipe for target 'cnutil/libcnutil.so' failed
make[2]: *** [cnutil/libcnutil.so] Error 1
CMakeFiles/Makefile2:140: recipe for target 'cnutil/CMakeFiles/cnutil.dir/all' failed
make[1]: *** [cnutil/CMakeFiles/cnutil.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can you please suggest me how to compile it correct? OS is ubuntu 16.04, all requirements works fine, monero client also compiled without any issue

**Comment by xstillwill** [comment]
Check previously closed issues please :)

Am 30.06.2017 um 19:25 schrieb armpdq <notifications@github.com<mailto:notifications@github.com>>:


after 'cmake .' all fine. but when i run 'make' command - i got this:
root@dev:/home/monero-stratum# make
Scanning dependencies of target hashing
[ 25%] Building C object hashing/CMakeFiles/hashing.dir/src/hashing.c.o
[ 50%] Linking C shared library libhashing.so
[ 50%] Built target hashing
Scanning dependencies of target cnutil
[ 75%] Building CXX object cnutil/CMakeFiles/cnutil.dir/src/cnutil.cpp.o
[100%] Linking CXX shared library libcnutil.so
/usr/bin/ld: cannot find -lcryptonote_core
/usr/bin/ld: cannot find -lcryptonote_basic
/usr/bin/ld: cannot find -lcommon
/usr/bin/ld: cannot find -lringct
collect2: error: ld returned 1 exit status
cnutil/CMakeFiles/cnutil.dir/build.make:99: recipe for target 'cnutil/libcnutil.so' failed
make[2]: *** [cnutil/libcnutil.so] Error 1
CMakeFiles/Makefile2:140: recipe for target 'cnutil/CMakeFiles/cnutil.dir/all' failed
make[1]: *** [cnutil/CMakeFiles/cnutil.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can you please suggest me how to compile it correct? OS is ubuntu 16.04, all requirements works fine, monero client also compiled without any issue

-

**Comment by armpdq** [comment]
i'm sorry, sir, but i checked all that issues before open new one. i did all as described in readme and tried with go 1.6 and 1.8 also

**Comment by armpdq** [comment]
with #16  and #17 i solved compile issue. but now when i run monerod i got segmentation failed
here is debug info, boost version is recommended 1.58
Starting program: /home/monero-v0.10.3.1/monerod 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2017-06-30 23:56:40.495	    7ffff7fe7740	INFO 	global	contrib/epee/src/mlog.cpp:145	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO
2017-06-30 23:56:40.495	    7ffff7fe7740	INFO 	global	src/daemon/main.cpp:282	Monero 'Wolfram Warptangent' (v0.10.3.1-release)
2017-06-30 23:56:40.495	    7ffff7fe7740	INFO 	global	src/daemon/protocol.h:55	Initializing cryptonote protocol...
2017-06-30 23:56:40.495	    7ffff7fe7740	INFO 	global	src/daemon/protocol.h:60	Cryptonote protocol initialized OK
2017-06-30 23:56:40.496	    7ffff7fe7740	INFO 	global	src/daemon/p2p.h:63	Initializing p2p server...
[New Thread 0x7ffff72e2700 (LWP 2225)]
[New Thread 0x7fffeeae1700 (LWP 2226)]
[New Thread 0x7ffff6ae1700 (LWP 2227)]
[New Thread 0x7ffff62e0700 (LWP 2228)]
[Thread 0x7ffff62e0700 (LWP 2228) exited]
[Thread 0x7ffff72e2700 (LWP 2225) exited]
[Thread 0x7fffeeae1700 (LWP 2226) exited]
[Thread 0x7ffff6ae1700 (LWP 2227) exited]

Thread 1 "monerod" received signal SIGSEGV, Segmentation fault.
0x00000000009c188f in boost::archive::detail::basic_iarchive_impl::load_pointer(boost::archive::detail::basic_iarchive&, void*&, boost::archive::detail::basic_pointer_iserializer const*, boost::archive::detail::basic_pointer_iserializer const* (*)(boost::serialization::extended_type_info const&)) ()

**Comment by sammy007** [comment]
If your monero daemon fails this is not a issue of this project.

**Comment by ostap-mykhaylyak** [comment]
Hi, i have same problem.
You can make an "plug&play" install script? Thanks

**Comment by sw4n** [comment]
@sammy007 It's strange.. but for the reason to compile and run your pool, I need to have source! files of monero. So why do you say that it's not problem of this project?) 
Sorry, I respect your work, and thank you for it. But I tried also to use compiled files, and it was failed to run your repository files :)

**Comment by sammy007** [comment]
Everything is simple if you follow instructions. And if `monerod` fails it's not a part of this project so you have to open an issue in https://github.com/monero-project/monero

**Comment by sw4n** [comment]
@sammy007 I've followed instructions, but it was not including hardware requirements. Monero wasn't compiling without enough RAM. Need to have 1,5-2 GB free. I guess you should add it to instruction, because monero doesn't.

**Comment by sammy007** [comment]
So I guess monero should add it to their requirements, not a 3rd party software like this one.
