### ISSUE TITLE
No hashrate

### ISSUE THREAD

**Issue by armpdq** [sammy007/monero-stratum#24]
Hello guys. i have two running pools on one machine (node-cryptonote-pool and this one).
When i mine, i got good hashrate on node-cryptonote-pool, on this one i dont see any hashrate in stats. config below: 
```
{
	"address": "xxxxxxxxx",
	"bypassAddressValidation": true,
	"bypassShareValidation": true,

	"threads": 2,

	"estimationWindow": "15m",
	"luckWindow": "24h",
	"largeLuckWindow": "72h",

	"blockRefreshInterval": "1s",

	"stratum": {
		"timeout": "15m",

		"listen": [
			{
				"host": "0.0.0.0",
				"port": 1111,
				"diff": 8000,
				"maxConn": 32768
			},
			{
				"host": "0.0.0.0",
				"port": 3434,
				"diff": 10000,
				"maxConn": 32768
			},
			{
				"host": "0.0.0.0",
				"port": 7878,
				"diff": 25000,
				"maxConn": 32768
			}
		]
	},

	"frontend": {
		"enabled": true,
		"listen": "0.0.0.0:8082",
		"login": "admin",
		"password": "",
		"hideIP": false
	},

	"upstreamCheckInterval": "15s",

	"upstream": [
		{
			"name": "Main",
			"host": "127.0.0.1",
			"port": 18081,
			"timeout": "10s"
		}
	],

	"newrelicEnabled": true,
	"newrelicName": "MyStratum",
	"newrelicKey": "xxxxxxx",
	"newrelicVerbose": true
}
```
Same difficulty, cryptonote is on 7777, this pool on 7878. Please suggest anything, it's really weird

**Comment by armpdq** [comment]
also if i run two instances to mine - i see only one miner instead of two.
<img width="952" alt="screen shot 2017-07-04 at 11 20 29 am" src="https://user-images.githubusercontent.com/18067800/27819358-e905a7e8-60aa-11e7-8416-0a88d8637d84.png">

**Comment by cwz0522** [comment]
Need more information to debug, like messages while starting monero-stratum and get shares, and if your miners has started to mine and get any shares? It seems that monero-stratum need shares to calculate hashrate.

**Comment by armpdq** [comment]
solved, thanks :)
