### ISSUE TITLE
Please update How To in README

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [sammy007/monero-stratum#27]
Full list of commands:

apt-get update && apt-get upgrade

apt-get install git cmake build-essential libssl-dev pkg-config libboost-all-dev

git clone https://github.com/monero-project/monero.git
cd monero
git checkout v0.10.3
cmake -DBUILD_SHARED_LIBS=1 .
make
cd ..

apt-get install golang
git clone https://github.com/sammy007/monero-stratum.git
cd monero-stratum
cmake .
make

export GOPATH=~/go
go get github.com/goji/httpauth
go get github.com/yvasiyarov/gorelic
go get github.com/gorilla/mux

go build -o pool main.go

mv config.example.json config.json
nano config.json

./pool config.json

**Comment by sammy007** [comment]
Added some, not sure we need a blind guide, people must understand basics, otherwise they belong to pool.
