### ISSUE TITLE
Error occured while polling proxy state.

### ISSUE THREAD

**Issue by BurtonChia** [sammy007/monero-stratum#28]
Hi I've  managed to get the pool running. But I get this error message when I visit the webpage:

`An error occured while polling proxy state. Make sure proxy is running.`

Any idea what's the issue?

**Comment by sammy007** [comment]
I have no clue about your setup, web page polls `/stats`. Open browser console and check for errors.

**Comment by BurtonChia** [comment]
Hi, where is /stats located? I don't see it in the www folder. 

I'm running it on an AWS instance, with lighttpd as the web server. My miner is able to connect to it and receive jobs....the pool output also confirms this.

However, I'm not able to view the webpage.

**Comment by sammy007** [comment]
You don't need web server, run it without it. I bet you misconfigured web server. Bind frontend to external IP and access it via your browser.

**Comment by sammy007** [comment]
if you need web server you have to configure it as reverse-proxy, start without, make sure it works and only then play further.

**Comment by BurtonChia** [comment]
Got it to work without the web server. Thanks for the help.

**Comment by shed909** [comment]
Sorry to dig this up, @BurtonChia can you comment on how you got it working? I'm attempting to bind frontend to my external IP and it gives me "<PUBLIC IP>:8082: bind: cannot assign requested address".
I'm digging through the repo and can't seem to put it together. How did you end up configuring yours?
