### ISSUE TITLE
pool

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [sammy007/monero-stratum#29]
I really like this project.
Do you think there will be a pool version?
Like this: https://github.com/zone117x/node-cryptonote-pool

At the moment i'm working on docker ( alpine linux ) image based on your project ( With material design template  ) .

More pool less centralization 👍

**Comment by sammy007** [comment]
No plans. There is FFS funded fork of nodejs pool, must work.

**Comment by ostap-mykhaylyak** [comment]
I see this https://github.com/sammy007/go-cryptonote-pool.git

Any update?
