### ISSUE TITLE
Web-UI reports only 1 miner

### ISSUE THREAD

**Issue by BurtonChia** [sammy007/monero-stratum#30]
Hi,

How do i get the web-UI to show the individual miners? The pool output log indicates I have 11 miners connected, but I only see 1 miner on the web-UI with the reported hashrate as the sum of all 11 miners.

**Comment by ostap-mykhaylyak** [comment]
I tested with 8 miners, and all ok.
Compile error?

**Comment by BurtonChia** [comment]
what did you set for username on your miners? 

If minig to the pool, I'd put<wallet_address>:<worker_id>. Now I'm just putting <worker_id>.

**Comment by ostap-mykhaylyak** [comment]
"pool_address" : "51.15.73.163:3333",
"wallet_address" : "43nTRGJivRiLniUternVZWF5yBVD8GLoRc3zowNeCMxyPfssZJBySVve8RZSPbFWoRFfjDbVGwYJPJFKppF4eQiF6ruRJAy.ASUSCPU",
"pool_password" : "x",

On monero-stratum show ASUSCPU

**Comment by BurtonChia** [comment]
got it. Thanks.
