### ISSUE TITLE
Miner share calculations are incorrect

### ISSUE THREAD

**Issue by nitronick600** [sammy007/monero-stratum#32]
See https://github.com/sammy007/monero-stratum/blob/master/go-pool/stratum/miner.go#L166

A validShare is added to the miner before the difficulty of the hash is checked.  In the case of a low difficulty share, both validShare and invalidShare are incremented.

**Comment by PedroD** [comment]
can this issue be fixed?

**Comment by rippaio** [comment]
Hmm.  Strange to close this so suddenly

**Comment by sammy007** [comment]
@rippaio what exactly is wrong with it?

https://github.com/sammy007/monero-stratum/commit/0a51384b1dc7f5d85ad0e9d4344bba70167e0807

Test this fix, report if something is wrong with it.
