### ISSUE TITLE
I get error on make (ubuntu 16.04)

### ISSUE THREAD

**Issue by dpark77** [sammy007/monero-stratum#35]
/monero$ sudo make
[  0%] Built target version
[  7%] Built target libminiupnpc-static
[ 45%] Built target unbound
[ 46%] Built target lmdb
[ 56%] Built target obj_crypto
[ 57%] Built target crypto
[ 59%] Built target epee
[ 65%] Built target obj_common
[ 65%] Built target common
[ 67%] Built target obj_ringct
[ 70%] Built target obj_cryptonote_basic
[ 70%] Built target cryptonote_basic
[ 70%] Built target ringct
[ 72%] Built target obj_cryptonote_core
[ 74%] Built target blocks
[ 74%] Built target obj_blockchain_db
[ 74%] Built target blockchain_db
[ 75%] Built target cryptonote_core
[ 76%] Built target obj_mnemonics
[ 77%] Built target mnemonics
[ 78%] Built target obj_rpc
[ 79%] Building CXX object src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/cryptonote_protocol_handler-base.cpp.o
In file included from /monero/src/cryptonote_protocol/../../../src/cryptonote_core/cryptonote_core.h:44:0,
                 from /monero/src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp:75:
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/tx_pool.h:250:46: error: ‘tx_backlog_entry’ was not declared in this scope
     void get_transaction_backlog(std::vector<tx_backlog_entry>& backlog) const;
                                              ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/tx_pool.h:250:62: error: template argument 1 is invalid
     void get_transaction_backlog(std::vector<tx_backlog_entry>& backlog) const;
                                                              ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/tx_pool.h:250:62: error: template argument 2 is invalid
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/tx_pool.h:456:37: error: ‘txpool_tx_meta_t’ has not been declared
     bool is_transaction_ready_to_go(txpool_tx_meta_t& txd, transaction &tx) const;
                                     ^
In file included from /monero/src/cryptonote_protocol/../../../src/cryptonote_core/cryptonote_core.h:45:0,
                 from /monero/src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp:75:
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/blockchain.h:884:47: error: ‘txpool_tx_meta_t’ does not name a type
     void add_txpool_tx(transaction &tx, const txpool_tx_meta_t &meta);
                                               ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/blockchain.h:885:59: error: ‘txpool_tx_meta_t’ does not name a type
     void update_txpool_tx(const crypto::hash &txid, const txpool_tx_meta_t &meta);
                                                           ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/blockchain.h:888:5: error: ‘txpool_tx_meta_t’ does not name a type
     txpool_tx_meta_t get_txpool_tx_meta(const crypto::hash& txid) const;
     ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/blockchain.h:891:76: error: ‘txpool_tx_meta_t’ does not name a type
  bool for_all_txpool_txes(std::function<bool(const crypto::hash&, const txpool_tx_m
                                                                         ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/blockchain.h:891:124: error: expected ‘::’ before ‘,’ token
 st crypto::hash&, const txpool_tx_meta_t&, const cryptonote::blobdata*)>, bool incl
                                                                         ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/blockchain.h:891:124: error: expected identifier before ‘,’ token
In file included from /monero/src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp:75:0:
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/cryptonote_core.h:435:42: error: ‘tx_backlog_entry’ was not declared in this scope
      bool get_txpool_backlog(std::vector<tx_backlog_entry>& backlog) const;
                                          ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/cryptonote_core.h:435:58: error: template argument 1 is invalid
      bool get_txpool_backlog(std::vector<tx_backlog_entry>& backlog) const;
                                                          ^
/monero/src/cryptonote_protocol/../../../src/cryptonote_core/cryptonote_core.h:435:58: error: template argument 2 is invalid
src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/build.make:62: recipe for target 'src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/cryptonote_protocol_handler-base.cpp.o' failed
make[2]: *** [src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/cryptonote_protocol_handler-base.cpp.o] Error 1
CMakeFiles/Makefile2:1537: recipe for target 'src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/all' failed
make[1]: *** [src/cryptonote_protocol/CMakeFiles/obj_cryptonote_protocol.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`
Any ideas why I'm getting all these errors? thanks

**Comment by sammy007** [comment]
Monero daemon compilation issues belongs to monero issue tracker. You must use stable version of daemon with this stratum.
