### ISSUE TITLE
hash-ops.h not found

### ISSUE THREAD

**Issue by dams114** [sammy007/monero-stratum#36]
Hi,
I took a look in posted issues ad could not find an answer.
I am on MACOS and followed (I hope) every steps until 
Build stratum:
MONERO_DIR=/path/to/monero cmake . (it works)
make  (doesn't work)

When I execute the make command, I get this :
[ 25%] Building C object hashing/CMakeFiles/hashing.dir/src/hashing.c.o
/Users/Damien/monero/monero-stratum/hashing/src/hashing.c:1:10: fatal error: 'crypto/hash-ops.h' file not found
#include "crypto/hash-ops.h"
         ^
1 error generated.
make[2]: *** [hashing/CMakeFiles/hashing.dir/src/hashing.c.o] Error 1
make[1]: *** [hashing/CMakeFiles/hashing.dir/all] Error 2
make: *** [all] Error 2

**Comment by sammy007** [comment]
`MONERO_DIR` must point to correct stable (tagged) compiled monero source tree.
