### ISSUE TITLE
noob about wallet question

### ISSUE THREAD

**Issue by mhejek** [sammy007/monero-stratum#37]
im new here.
wanna try my own pool
i always get message . 
2017/09/01 17:57:15 Valid share at difficulty 16000/21377
2017/09/01 17:58:16 Unknown RPC method: &{0xc82032f2e0 keepalived 0xc82032f380}
 
second.
do i have to make my won walletid thatd created by monero-wallet-cli  in config.json?
do i have to always  run  monero-wallet-rpc ?
what service does monero-stratum service must run beside monerod?

**Comment by sammy007** [comment]
1) Yes
2) No
3) monero-stratum + monerod.
