### ISSUE TITLE
Unable to make direct JSON-RPC calls

### ISSUE THREAD

**Issue by RationalCoding** [sammy007/monero-stratum#43]
Existing Stratum libraries do not work with this server due to it not supporting the "mining.subscribe" method (which I assume is Bitcoin-specific).

I am attempting to write one, but all JSON-RPC calls to this server hang. The server works fine with Monero miners.

```javascript
var jayson = require('jayson')

var client = jayson.client.tcp({
  port: '0.0.0.0',
  host: 1111
})

// The below call will hang forever
client.request('login', {login: "", pass:"", agent:"USER_AGENT"}, 1, function(err, response) {
  if(err) throw err
  console.log(response)
})
```

Only after interrupting the client's process will the server respond to the call:
```
2017/09/15 22:17:29 Stratum listening on 0.0.0.0:1111
2017/09/15 22:17:30 New block to mine on Main at height 1400001, diff: 31118527843, prev_hash: 772b808176cb868bee556f34291d4e7f4b68e8ec469677dbda150af63b4123fd

// The call is made and hangs for several minutes, then I interrupt it

2017/09/15 22:17:43 Miner connected 0@127.0.0.1
2017/09/15 22:17:43 Client disconnected 127.0.0.1
```

The connection is clearly being made, but no response is coming from the server. Any JSON-RPC library I use (or even sending the tcp packets myself) behaves the same way, regardless of language. Other JSON-RPC servers do not behave this way.

Any help with this would be appreciated.

**Comment by brinstarnetworks** [comment]
cryptonight stratum differs from other coins considerably, so don't expect other libraries to work out of the box.

anyway, just tested sending a payload manually and the server responds as expected - confirm the actual payload you're sending on the wire?

{"method":"login","params":{"login":"asdf","pass":"x","agent":"test/1.2.3"},"id":1}

**Comment by RationalCoding** [comment]
I was forgetting a `\n` at the end of the payload. Apologies, it's been awhile since I've delved into raw.

`{"method":"login","params":{"login":"asdf","pass":"x","agent":"test/1.2.3"},"id":1}\n`
