### ISSUE TITLE
Diff in config

### ISSUE THREAD

**Issue by entire-media** [sammy007/monero-stratum#45]
Hi there it's not a error.

But one question

In example.conf there are multiple ports with different diff which should I use like nanopool div is 120001 ?

Thank you

**Comment by brinstarnetworks** [comment]
you need to choose a difficulty suitable for the workers connecting to that port. if you don't know how to determine that, then go test your miners against a pool and see what your average vardiff turns out to be

**Comment by entire-media** [comment]
Thank you
