### ISSUE TITLE
miners appear under same ip address (despite setting different worker name)

### ISSUE THREAD

**Issue by melpheos** [sammy007/monero-stratum#49]
30 workers, many of them have a different worker name (set in pass as 1:none@none.com and 2:none@none.com in xmrig)

**Comment by masonr** [comment]
+1. Same issue here.

Only IP listed is the first worker that connected under ID 0.  Console output shows that multiple miners are being recognized ("Broadcasting new jobs to n miners." I suppose that would suggest that it's just the web interface that is grouping all the miners under one ID.

**Comment by melpheos** [comment]
Haaaaaa got it :)
Set your payment adress as xxxxxxxxxxxxxxxxxxxxx.id (where id is the id of your worker)
https://www.reddit.com/r/MoneroMining/comments/665c4v/how_to_put_a_worker_id_on_xmrstak_minner/

**Comment by masonr** [comment]
Ahh... Cheers! That did the trick.
