### ISSUE TITLE
upstream fails

### ISSUE THREAD

**Issue by alek-01** [sammy007/monero-stratum#53]
hi, sammy007

last 20 hours i'm testing monero-stratum  and have got 14  **upstream fails**:

**Upstream Main didn't pass check: Post http://127.0.0.1:18081/json_rpc: net/http: request canceled (Client.Timeout exceeded while awaiting headers)**

what does it mean?

Ubuntu 16.04.3 LTS
running Monero 'Helium Hydra' (v0.11.0.0-5f7cdde) and have all rpc calls without any fails according to https://getmonero.org/resources/developer-guides/daemon-rpc.html 

tnx in advance

**Comment by sammy007** [comment]
It means that there is a connection timeout between stratum and daemon rpc.

**Comment by alek-01** [comment]
i see
and what a reason what do think?

**Comment by sammy007** [comment]
The reason is bed connectivity, high refresh interval, something else.

**Comment by alek-01** [comment]
tnx

default settings was used except diff ;)
i'll play around with diff

**Comment by sammy007** [comment]
Diff is not related to rpc failures. Check connectivity. If both daemon and stratum on the same host you must connect via 127.0.0.1 if it still fails something is wrong with daemon.
