### ISSUE TITLE
Website "issue"

### ISSUE THREAD

**Issue by Qurmo** [sammy007/monero-stratum#56]
In short, after doing everything over from scratch.  Meaning format and reinstall Linux Ubuntu Server 16.04 LTS.   🥇   IT WORKED 🥇 

... but for some kinda reason the website give's me 
"An error occured while polling proxy state. Make sure proxy is running."
what am I doing wrong?  I copied the content of the "www" into /var/www/html/

**Comment by sammy007** [comment]
Its not a website. It's self hosted UI, don't touch it.

**Comment by Qurmo** [comment]
how do I acces it then?

**Comment by sammy007** [comment]
https://github.com/sammy007/monero-stratum/blob/master/config.example.json#L41

**Comment by Qurmo** [comment]
still have to be doing something wrong, corrected the mistake I made before, changed the ip as pointed out in the link above to my local ip:80, i get the demand for login & password wich I enter but then I get "404 page not found".  So sorry to bug you with this.
