### ISSUE TITLE
Running as a service

### ISSUE THREAD

**Issue by Qurmo** [sammy007/monero-stratum#57]
For starters I want to thank you for all the work you've put into this, and the fact you want to share this with us.

Now that I finally got things working, is it possible to run the "./monero-stratum /home/pooldaemon/monero-stratum/config.json" command as a service? on linux server?

**Comment by sammy007** [comment]
Must be easy if you can learn how to use upstart or systemd.

**Comment by sammy007** [comment]
Try to customise this one https://github.com/sammy007/open-ethereum-pool/blob/master/misc/upstart.conf

**Comment by Qurmo** [comment]
Would the below look correct?

# Monero Private Pool
description "Private Monero Pool"

env DAEMON=/home/pooldaemon/monero-stratum/build/bin/monero-stratum
env CONFIG=/home/pooldaemon/monero-stratum/config.json

start on filesystem or runlevel [2345]
stop on runlevel [!2345]

setuid main
setgid main

kill signal INT

respawn
respawn limit 10 5
umask 022

pre-start script
	test -x $DAEMON || { stop; exit 0; }
end script

# Start
script
	exec $DAEMON $CONFIG
end script

**Comment by sammy007** [comment]
You want me to parse it in a head or test for you?

**Comment by sammy007** [comment]
Just put this file in a right place in `/etc` and try yourself. If it's incorrect it won't hurt your computer. Looks good tho.

**Comment by sammy007** [comment]
```
setuid main
setgid main
```

`main` it's a username for this example config, your username is likely different.
