### ISSUE TITLE
RPC connection refused

### ISSUE THREAD

**Issue by vphelipe** [sammy007/monero-stratum#58]
2017/10/05 19:50:27 Error while refreshing block template: Post http://74.208.210.76:18081/json_rpc: dial tcp 74.208.210.76:18081: getsockopt: connection refused

Solution?

**Comment by sammy007** [comment]
The solution is correct configuration.

**Comment by vphelipe** [comment]
Sorry but I followed all the steps, do I have to install anything else? I'm n00b

**Comment by sammy007** [comment]
This issue tracker is not for training.
