### ISSUE TITLE
Stratum compatibility with xmrig

### ISSUE THREAD

**Issue by favoritelotus** [sammy007/monero-stratum#60]
It's been discovered that xmrig miner is not working with the pool. 
When I try connecting  to the pool with xmrig miner, the following errors occure:

  xmrig -a cryptonight-lite -o stratum+tcp://10.29.135.1:1111 -u  MYWALLET -p x -t 12 --user-agent "DDD"
 * VERSIONS:     XMRig/2.4.0 libuv/1.10.2 gcc/4.8.5
 * HUGE PAGES:   available, enabled
 * CPU:          Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz (1) x64 AES-NI
 * CPU L2/L3:    1.5 MB/12.0 MB
 * THREADS:      12, cryptonight-lite, av=2, donate=5%
 * POOL #1:      10.29.135.1:1111
 * COMMANDS:     hashrate, pause, resume
[2017-10-08 11:00:34] [10.29.135.1:1111] login error code: 3
[2017-10-08 11:00:40] [10.29.135.1:1111] login error code: 3

I tried to start xmrig miner with various  options but result is always the same. 
However, other miners such as cpuminer or minerd  works fine with the pool.

**Comment by tsudmi** [comment]
I have the same issue.

**Comment by sammy007** [comment]
I have no idea why this miner is special, need a community help. Maybe @stoffu can shed a light.

**Comment by stoffu** [comment]
@favoritelotus 
I'm using XMRig and monero-stratum with Aeon mining setup on OSX, and I don't see any problems. The error message `login error code: 3` seems to come from this line:

https://github.com/xmrig/xmrig/blob/a3297b9ea4154599dc6a95bb40d73008a972c95b/src/net/Client.cpp#L208

Which indicates that there's something wrong when parsing the `job_id`. I'm not sure how to solve the problem. Perhaps restarting the daemon and stratum pool might help?

**Comment by favoritelotus** [comment]
@stoffu 

Strange that your xmrig miner is working monero-stratum pool.
What xmrig miner version are you using? I've downloded and build the latest version from github.
Maybe the older versions don't have such problems.

**Comment by stoffu** [comment]
@favoritelotus I’m using the latest version of XMRig 2.4.0.

**Comment by favoritelotus** [comment]
OK. I figured out where the problem is lurking .
xmrig checks jobid in setId() method of the class JobID which must be at least 4 bytes long to pass the check.
if jobid is less than 4 bytes, the function returns false, which is an error. I have checked that jobId starts from zero and therefor cannot be four bytes long. 
So here is the patch I made that fixes the problem.  You just need to apply the patch and rebuild xmrig following the steps bellow:

git clone https://github.com/xmrig/xmrig.git
cd xmrig
patch -p1 < xmrig.patch
mkdir build
cd build
cmake3 .. -DCMAKE_BUILD_TYPE=Release
make 

diff -ur xmrig_orig/src/net/JobId.h xmrig/src/net/JobId.h
--- xmrig_orig/src/net/JobId.h	2017-10-09 03:22:24.733266554 -0400
+++ xmrig/src/net/JobId.h	2017-10-09 03:23:04.392712944 -0400
@@ -63,7 +63,7 @@
         }
 
         const size_t size = strlen(id);
-        if (size < 4 || size >= sizeof(m_data)) {
+        if (size >= sizeof(m_data)) {
             return false;
         }

 

Good luck!

**Comment by favoritelotus** [comment]
The patch is incorrectly formatted with code insertion. Sorry, cannot do anything with this.

**Comment by sammy007** [comment]
You should submit a patch to xmrig because it's weird "requirement".

**Comment by sammy007** [comment]
Must be fixed now in miner repo.

**Comment by favoritelotus** [comment]
Good news!
