### ISSUE TITLE
running with error

### ISSUE THREAD

**Issue by Jackie0911** [sammy007/monero-stratum#61]
i got an error when i execute ./build/bin/monero-stratum config.json

Upstream Main didn't pass check: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused
Error while refreshing block template: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused

what should i do for this?
thank you.

**Comment by stoffu** [comment]
Is your daemon running with port 18081 open? Do you see correct responses if you send some daemon RPC commands? https://getmonero.org/resources/developer-guides/daemon-rpc.html

For example:
```
curl -X POST http://127.0.0.1:18081/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"getblockcount"}' -H 'Content-Type: application/json'
```

**Comment by Jackie0911** [comment]
error
curl: (7) Failed to connect to 127.0.0.1 port 18081: Connection refused

**Comment by sammy007** [comment]
So run a monero node.

**Comment by sammy007** [comment]
To be clear, you must run a `monerod` because pool must connect to it via rpc. You are getting connection refused because there is no a full node to connect to on 127.0.0.1 port 18081.
