### ISSUE TITLE
How to get this to autostart on bootup.

### ISSUE THREAD

**Issue by theyhavelanded** [sammy007/monero-stratum#62]
I have tried setting it up as a service but it fails.

Any suggestions? I am able to get monerod to run as a service without any issues. I tried changing the config for this but it fails and exits.

[Unit]
Description=Monero Full Node
After=network.target

[Service]
User=monero
Group=monero
WorkingDirectory=~
RuntimeDirectory=monero

Type=forking
PIDFile=/run/monero/monerod.pid

ExecStart=/usr/bin/monerod --config-file /etc/monerod.conf \
    --detach --pidfile /run/monero/monerod.pid

[Install]
WantedBy=multi-user.target

**Comment by sammy007** [comment]
https://github.com/monero-project/monero/blob/master/utils/systemd/monerod.service
