### ISSUE TITLE
Nicehash Support?

### ISSUE THREAD

**Issue by jonhitchcock** [sammy007/monero-stratum#63]
# Nicehash Support

When trying to connect Nicehash mining pool getting Username and Password Authentication Error. Is it possible to point Nicehash to this proxy? (Leasing Hashpower from Nicehash --> Proxy)

Tried:
-u "XRMADDR"
-p "x"

-u "XRMADDR.wrk1"
-p "x"

-u empty()
-p empty()

-u "admin"
-p (password in .conf)

Notes:
Node and Proxy are is externally located. 
CPU & GPU from multiple ip address able to mine.

**Comment by sammy007** [comment]
Disable address validation and use anything for password and username.

**Comment by sammy007** [comment]
If it does not work you must post logs.

**Comment by jonhitchcock** [comment]
Thank you, that did the trick.
