### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by Falesco** [sammy007/monero-stratum#64]
Im trying to install the stratum on my CentOS6 VPS. But getting this error:

[root@9792542 monero]# make
[  1%] Built target version
[  1%] Building C object external/miniupnpc/CMakeFiles/libminiupnpc-static.dir/igd_desc_parse.c.o
cc1: error: invalid option argument '-Ofast'
cc1: warning: unrecognized command line option "-Wno-unused-result"
make[2]: *** [external/miniupnpc/CMakeFiles/libminiupnpc-static.dir/igd_desc_parse.c.o] Error 1
make[1]: *** [external/miniupnpc/CMakeFiles/libminiupnpc-static.dir/all] Error 2
make: *** [all] Error 2

**Comment by sammy007** [comment]
If you can't compile monero this is not a stratum issue.

**Comment by Falesco** [comment]
hey Sammy, i know its a gcc thing right? It seems that i have to change the -Ofast option.. But where?
Thanks for your support!

**Comment by sammy007** [comment]
I have no idea. https://github.com/monero-project/monero
