### ISSUE TITLE
worker identification

### ISSUE THREAD

**Issue by da-player** [sammy007/monero-stratum#65]
Is there any way to identify workers? I want to know how much each worker mined / day and I also want to build a custom web interface to show these results based on worker login / id something, I can't rely only on IP because it might be dynamic.

**Comment by stoffu** [comment]
You can set the miner's wallet address to an arbitrary integer after a period. Here's an example with XMRig:

```javascript
    "pools": [
        {
            "url": "your-starum.com:3333",
            "user": ".1000",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]
```

This number gets interpreted as the "worker ID" in the web interface.

**Comment by da-player** [comment]
thanks @stoffu I will give it a try!
