### ISSUE TITLE
Error while refreshing block template

### ISSUE THREAD

**Issue by Roberthasalltehswag** [sammy007/monero-stratum#66]
Sorry this question seems a bit stupid, I cant seem to fix my issue
#### System information

OS & Version: Linux

#### Expected behaviour
Everything working normally

#### Actual behaviour
Cannot connect minter to pool

#### Steps to reproduce the behaviour
Ran the progrem

## Console
$: sudo ./build/bin/monero-stratum config.json
2017/11/01 20:53:20 Loading config: /home/wob/monero-stratum/config.json
2017/11/01 20:53:20 Running with 2 threads
2017/11/01 20:53:20 Upstream: Main => http://127.0.0.1:18081/json_rpc
2017/11/01 20:53:20 Default upstream: Main => http://127.0.0.1:18081/json_rpc
2017/11/01 20:53:20 Set block refresh every 1s
2017/11/01 20:53:20 Stratum listening on 0.0.0.0:5555
2017/11/01 20:53:20 Stratum listening on 0.0.0.0:3333
2017/11/01 20:53:20 Stratum listening on 0.0.0.0:1111
#Repetition Starts here
2017/11/01 20:53:20 Error while refreshing block template: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused
2017/11/01 20:53:21 Error while refreshing block template: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused
2017/11/01 20:53:22 Error while refreshing block template: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused
2017/11/01 20:53:23 Error while refreshing block template: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused
2017/11/01 20:53:24 Error while refreshing block template: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused
2017/11/01 20:53:25 Upstream Main didn't pass check: Post http://127.0.0.1:18081/json_rpc: dial tcp 127.0.0.1:18081: getsockopt: connection refused
#Repeats

## Output from miner
(started a few seconds Console is setup, pointed at the pool with no username or password)

[2017-11-01 21:00:06] : Connecting to pool 192.168.0.45:1111 ...
[2017-11-01 21:00:06] : Connected. Logging in...
[2017-11-01 21:00:06] : SOCKET ERROR - Job not ready
[2017-11-01 21:00:06] : SOCKET ERROR - RECEIVE error: socket closed
[2017-11-01 21:00:06] : Pool connection lost. Waiting 10 s before retry (attempt 1).

**Comment by sammy007** [comment]
Do you understand that you must run `monerod`?

**Comment by Roberthasalltehswag** [comment]
Oh, does it need to run at the same time. I thought i just had to let it download the blockchain and then I could ignore it, thanks.
