### ISSUE TITLE
Compile/Make error with Stratum.

### ISSUE THREAD

**Issue by Falesco** [sammy007/monero-stratum#67]
I finally got the Monero installed, so now when i go one withe making the Stratum, im getting this errors:
`root@9792542:~/monero/monero-stratum# make
[ 20%] Building CXX object cnutil/CMakeFiles/cnutil.dir/src/cnutil.cpp.o
/root/monero/monero-stratum/cnutil/src/cnutil.cpp:3:54: fatal error: cryptonote_basic/cryptonote_format_utils.h: No such file or directory
compilation terminated.
cnutil/CMakeFiles/cnutil.dir/build.make:62: recipe for target 'cnutil/CMakeFiles/cnutil.dir/src/cnutil.cpp.o' failed
make[2]: *** [cnutil/CMakeFiles/cnutil.dir/src/cnutil.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'cnutil/CMakeFiles/cnutil.dir/all' failed
make[1]: *** [cnutil/CMakeFiles/cnutil.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
root@9792542:~/monero/monero-stratum#
`

```
> The cmake .  i had to to before this step went perfect:
> 
> root@9792542:~/monero/monero-stratum# MONERO_DIR=/path/to/monero cmake .
> Using Monero source from env /path/to/monero
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   thread
> --   system
> --   program_options
> --   date_time
> --   filesystem
> --   chrono
> --   atomic
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /root/monero/monero-stratum
```

**Comment by Falesco** [comment]
Thanks for all help and advice!

**Comment by stoffu** [comment]
`/path/to/monero` isn't meant to be literally put like that; you should substitute it with the actual directory of the monero repository on your computer.

**Comment by Falesco** [comment]
Thanks for the quick reply stoffu!

I installed the monero, than installed the stratum in the moner dir.
So i have `/monero/monero-stratum/`

**Comment by Falesco** [comment]
or should i NOT install the stratum in monero dir? and just also install stratum in the home dir?

**Comment by Falesco** [comment]
ohhww stupid haha i should be like : MONERO_DIR=/home/root/monero etc
