### ISSUE TITLE
Webinterface "frontend" Error 404

### ISSUE THREAD

**Issue by gregmoulis** [sammy007/monero-stratum#68]
Hi,

Thank you for your work.
When I launch the monero-stratum with the config file, I can open the authentification on the port 8082 but after authnetification I have a 404 error.

Have you an idea?

Thank you

**Comment by sammy007** [comment]
Launch it right from from repo directory. You must `cd monero-stratum` then launch it.

**Comment by gregmoulis** [comment]
It works fin, many thanks
