### ISSUE TITLE
Miners information on webpage

### ISSUE THREAD

**Issue by gregmoulis** [sammy007/monero-stratum#69]
Hi,

I have connected to XMRIG, on the local status page I saw only one.
On the server, I view sending job to 2 miners...

Thank you

**Comment by travelbuzz** [comment]
Can you make a video on how to.run it from scratch I.am a newbie.



Thank you

**Comment by sammy007** [comment]
I guess it's a dev fee connection from this miner. Have no idea how it's implemented tbh.

**Comment by gregmoulis** [comment]
It' strange because, I only see 1 miner, the local minor but the Hash Rate increase when I add a new miner...

**Comment by sammy007** [comment]
You must use `something.WorkerID` as username to see separate workers. Either disable address validation or use `<address>.WorkerID` as username.
