### ISSUE TITLE
Do you have to start_mining on monerod to use monero-stratum

### ISSUE THREAD

**Issue by TNuzzi** [sammy007/monero-stratum#70]
More of a question then an issue.  Do you have execute `monerod start_mining <address>` along with starting `monero-stratum`?  The documentation is not clear.  I assume so but could not find any reference to starting the miner on `monerod`.

**Comment by stoffu** [comment]
No. The role of `monerod` is to provide block templates to the stratum pool which then distributes them to its connected miners. It's not a good idea to run the miner inside `monerod` since it's generally much less efficient than other dedicated miners.

**Comment by TNuzzi** [comment]
Ah got it, thanks.

**Comment by sammy007** [comment]
The documentation is clear if you know basics.
