### ISSUE TITLE
Update Documnetations

### ISSUE THREAD

**Issue by gmareater** [sammy007/monero-stratum#72]
hi

first of all: thanx for your great work
your documentation was very neat and excellent,  but  small room for improvement
1.please mention to your users the need to run monerod 
just put blow line from your closed issues in your documentation, (it took me 1 hour to find it, and i'm good with searching) 
"To be clear, you must run a monerod because pool must connect to it via rpc. You are getting connection refused because there is no a full node to connect to on 127.0.0.1 port 18081."
2. address people  common problems (you already have them in your closed issues)

other than this, Really nice work
keep going bro

**Comment by travelbuzz** [comment]
Can you please make a tutorial video of the whole process

Thank.you

**Comment by sammy007** [comment]
If README is not enough you should not continue. It's obvious that you need a daemon for mining. Without basic knowledge people should not use it. Currently it requires thousands of GPUs to mine solo, people with such power know everything required to set it up.

**Comment by stoffu** [comment]
FWIW I still solo mine with only one GPU and 5 CPUs totaling ~4kH/s 😄 
There's nothing wrong with solo mining at low hash rates - the total reward over a long enough time period should be no less than that from pool mining.

**Comment by gmareater** [comment]
It's an improvement, so whats wrong with it,
just add one simple line:
"To be clear, you must run a monerod because pool must connect to it via rpc. You are getting connection refused because there is no a full node to connect to on 127.0.0.1 port 18081."
