### ISSUE TITLE
Understanding how `util.GetTargetHex ` function works

### ISSUE THREAD

**Issue by kgritesh** [sammy007/monero-stratum#73]
Thanks a lot for a great library. I learned a lot about monero and mining pools from this code. However i had couple of questions which i am not able to understand. I guess this is not an issue as much as a request to understand how do we calculate target hash for a job.  As far as i understand  
 from [here](http://learnmeabitcoin.com/guide/difficulty#finding-the-target-using-the-difficulty)   
    
 `target = <max target> / difficulty`

However in the implementation we only take first 4 bytes of the target and reverse them. Infact i saw that even the other open source mining pools does the same thing. I have spent couple of days trying to figure this out, but have still been stumped. Would really appreciate if you could help with this

**Comment by xenhim** [comment]
I'M worried . I have been mining for a long time 20h . I have not seen any block yet.
http://35.197.138.224:8082/ :worried:

**Comment by sammy007** [comment]
Exactly like in node-cryptonote-pool.

**Comment by kgritesh** [comment]
@sammy007 Yes it does work exactly like node-cryptonote-pool, that i already checked, but was wondering if you could help met with logic behind it, i wasn't able to wrap my head around it. Thanks
