### ISSUE TITLE
Config File Listen Hosts

### ISSUE THREAD

**Issue by seangeleno** [sammy007/monero-stratum#74]
#### System information

Monero version: `monerod --version` or commit hash via `git rev-parse --short HEAD` if `master` branch

# [fda88c8d](https://github.com/monero-project/monero/commit/fda88c8d28d186afff84234356fb6e63222cbfb0)

Stratum commit hash: `git rev-parse --short HEAD`

# 56f4aee

OS & Version: Linux/OSX
#### Expected behaviour

```
"listen": [ // as single object in array; only using 1 daemon.
			{
				"host": "127.0.0.1",
				"port": 8101,
				"diff": 8000,
				"maxConn": 32768
			}
		]
```
# or
```
"listen":  // without array as i'm only running 1 daemon?
			{
				"host": "127.0.0.1",
				"port": 8101,
				"diff": 8000,
				"maxConn": 32768
			}
```
I thought about passing in 127.0.0.1 as I'm running the daemon on my local host, however, the upstream has that already. 
```
	"upstream": [ // is this designed as array for multiple objects? or would there always be just one
		{
			"name": "Main",
			"host": "127.0.0.1",
			"port": 18081,
			"timeout": "10s"
		}
	]
```
Kinda confused as to the 0.0.0.0 on front-end as well. Also, is admin static or does that refer to wallet name?
```
	"frontend": {
		"enabled": true,
		"listen": "127.0.0.1:8082",
		"login": "admin",
		"password": "",
		"hideIP": false
	}
```

#### Actual behaviour
```
	"stratum": {
		"timeout": "15m",

		"listen": [
			{
				"host": "0.0.0.0",
				"port": 1111,
				"diff": 8000,
				"maxConn": 32768
			},
			{
				"host": "0.0.0.0",
				"port": 3333,
				"diff": 16000,
				"maxConn": 32768
			},
			{
				"host": "0.0.0.0",
				"port": 5555,
				"diff": 16000,
				"maxConn": 32768
			}
		]
	},

	"frontend": {
		"enabled": true,
		"listen": "0.0.0.0:8082",
		"login": "admin",
		"password": "",
		"hideIP": false
	},,
	"upstream": [
		{
			"name": "Main",
			"host": "127.0.0.1",
			"port": 18081,
			"timeout": "10s"
		}
	]
```
#### Backtrace

````
[backtrace]
````

**Comment by sammy007** [comment]
`listen` is an array of stratum ports, miners connect to it. One or many.
`frontend` is a web interface.
`upstream` is an array of monero daemons. One or many.

**Comment by sammy007** [comment]
Of course you don't wanna close this.
