### ISSUE TITLE
cannot find block data

### ISSUE THREAD

**Issue by ziyaad30** [sammy007/monero-stratum#75]
I get this error, in my Miner app

cannot find block data:
{"id":4,"jsonrpc":"2.0","result":null,"error":{"code":-1,"message":"Blockexpired"}}
cannot convert blob data

Also, can someone confirm a successful block found?

**Comment by sammy007** [comment]
It's a stale share, worth nothing. Shares actually worth nothing if you mine solo unless it solves a block.

> Also, can someone confirm a successful block found?

Yes. I can confirm.
