### ISSUE TITLE
can i use this to build a mining pool? 

### ISSUE THREAD

**Issue by emanuelecesari** [sammy007/monero-stratum#79]
Sorry for the stupid question,
what is the difference between your project and this https://github.com/zone117x/node-cryptonote-pooonl#4-start-the-pool??
what i should use to build a mining pool?

**Comment by sammy007** [comment]
U must use node-cryptonote-pool.

**Comment by stoffu** [comment]
The difference is that node-cryptonote-pool counts shares sent from different miners separately and distributes the mining reward according to each miner's total shares, while monero-stratum assumes all the miners to be the same as the pool operator and sets the wallet address specified in its config as the recipient of the coinbase (i.e. it's for solo mining).
