### ISSUE TITLE
web question

### ISSUE THREAD

**Issue by asteroids1** [sammy007/monero-stratum#80]
Everything seems to be running fine. I can view the web page on my desktop. What do I change to view the web page on another system?

**Comment by stoffu** [comment]
If your other computers are on the same LAN, you’d just need to type that local IP (e.g. 192.168.1.x) and the port number you put in the config. If you want to access the web interface from outside your LAN, you’d need to set up things like dynamic DNS and configure your router to map the connection to the correct port.
