### ISSUE TITLE
Can you use this for other coins?

### ISSUE THREAD

**Issue by vanhalendlrband** [sammy007/monero-stratum#81]
This looks more up to date than other cryptonote software and they seem to only be able to run with old versions of node and ubuntu and i can't even get ubuntu 14 to work with my newer hardware and i can't seem to get the older nodes to detect when it comes to the other cryptonote pool software.

I'm really at the point where i'm stuck and would like to get something up and running for sumokoin as its the only thing i can realistically mine solo at this point. If i can use this software and adapt it to sumokoin that would be greatly appreciated.

Funny thing is i can get z-nomp running find with node but i keep getting node errors with any of these cryptonote softwares and i believe i'm getting them with this too but i was trying to use it with sumokoin so i'm not sure if you can do that or not i just assumed you could for solo mining.

If you can help me with this or help me get the other software running i'd be really appreciative i've been workin on it since 8am today and its now 12:35 and i'm just really stuck. I've tried sumokoin cryptonote pool and cryptonote pool and i believe i tried this one too. It's not so much that they don't work so much as i can't properly finish "make" on any of them. They always throw an error at some point.

It doesn't seem like anywhere else is even active on this stuff so if you have any idea what i'm doing wrong or if the fact i'm running ubuntu 17.04 is screwing me that would be fantastic. I just am dying to setup this pool for cryptonote like i did for equihash. That would be amazing please help!

**Comment by sammy007** [comment]
Try to link it with sumo code, just like in README, but with sumo. It must work because sumo is actually a copy of monero with premine.

I will never add direct support of sumo coin or electroneum because this project is FOSS and both sumo and electroneum are commercial projects. The former contains premine, the latter is just a plain scam and nothing else. Sumo can donate 1 BTC from it's premine for a dedicated branch, the same will cost 10 BTC to electroneum team.

You can't use it for equihash coins because it's a cryptonote stratum. There is a binaries on my github with devfee for ZCash/ZCL (pretty outdated tho). I also selling a repository access to my highly optimized equihash full stack pool (ZEC/ZCL/ZEN/BTG), the price is 1.25 BTC.

**Comment by vanhalendlrband** [comment]
Ok i'll give it a shot thank you.

**Comment by vanhalendlrband** [comment]
Would i just point, like in the instructions, at the sumokoin path versus the monero path and then everything else the same?

**Comment by vanhalendlrband** [comment]
Ok this is definitely where i'm stuck i can't seem to point it to the sumokoin wallet when you try to run cmake. Thats where i'm stuck. I even tried putting monero-stratum in the home directory but it won't even let me use make, it did let me put cmake into the sumokoin wallet but won't let me make afterwards as if i didn't even do anything

**Comment by vanhalendlrband** [comment]
[ 20%] Building C object hashing/CMakeFiles/hashing.dir/src/hashing.c.o
/home/hal9000/monero-stratum/hashing/src/hashing.c:1:29: fatal error: crypto/hash-ops.h: No such file or directory
 #include "crypto/hash-ops.h"
                             ^
compilation terminated.
hashing/CMakeFiles/hashing.dir/build.make:62: recipe for target 'hashing/CMakeFiles/hashing.dir/src/hashing.c.o' failed
make[2]: *** [hashing/CMakeFiles/hashing.dir/src/hashing.c.o] Error 1
CMakeFiles/Makefile2:123: recipe for target 'hashing/CMakeFiles/hashing.dir/all' failed
make[1]: *** [hashing/CMakeFiles/hashing.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Ok I got a little bit further. I was able to start the make but then i get this. I was able to point it to the sumokoin folder directly it confirmed it twice and it never got this far before so i assume i'm getting a little bit closer now.
Not sure how to get make past 20% now though totally stuck again but will keep trying. I anxiously await your reply if you know what i could be missing here.

**Comment by aerth** [comment]
Just encountered the same exact issue, you must have copy pasted `MONERO_DIR=/path/to/monero cmake .` directly.

Re-run that cmake command with the correct `MONERO_DIR` (which is the location where you cloned monero such as `/home/hal9000/src/monero`)

building monero-stratum requires the monero source code for header files. (.h)

```
$ make
Scanning dependencies of target hashing
[ 20%] Building C object hashing/CMakeFiles/hashing.dir/src/hashing.c.o
[ 40%] Linking C shared library libhashing.so
[ 40%] Built target hashing
Scanning dependencies of target cnutil
[ 60%] Building CXX object cnutil/CMakeFiles/cnutil.dir/src/cnutil.cpp.o
[ 80%] Linking CXX shared library libcnutil.so
[ 80%] Built target cnutil
Scanning dependencies of target build
[100%] Generating build/bin
github.com/goji/httpauth (download)
github.com/gorilla/mux (download)
github.com/yvasiyarov/gorelic (download)
github.com/yvasiyarov/go-metrics (download)
github.com/yvasiyarov/newrelic_platform_go (download)
github.com/goji/httpauth
github.com/gorilla/mux
github.com/sammy007/monero-stratum/pool
github.com/sammy007/monero-stratum/cnutil
github.com/sammy007/monero-stratum/hashing
github.com/sammy007/monero-stratum/rpc
github.com/yvasiyarov/go-metrics
github.com/yvasiyarov/newrelic_platform_go
github.com/sammy007/monero-stratum/util
github.com/sammy007/monero-stratum/stratum
github.com/yvasiyarov/gorelic
github.com/sammy007/monero-stratum
[100%] Built target build

```

**Comment by vanhalendlrband** [comment]
Maybe thats why i was trying to use this on Sumokoin

**Comment by vanhalendlrband** [comment]
Althought he said it should probably work with it, maybe its just some filename changes i have to do to match them, or do i need to do something else?

**Comment by vgalbur** [comment]
Good day! I run all commands to install stratum
Now I don't understand how to start stratum??? I type ./build/bin/monero-stratum config.json  but it write me -bash: ./build/bin/monero-stratum: No such file or directory . I edit config.json file with my address
