### ISSUE TITLE
Failed to parse wallet address

### ISSUE THREAD

**Issue by StiiCeva** [sammy007/monero-stratum#82]
#### System information

Ubuntu: 16.04 

#### Expected behaviour

I just finsihed the setup. I'm at sync with the network, created a wallet. I keep getting the following errors.

#### Actual behaviour

2017/12/03 08:22:15 Upstream Main didn't pass check: Failed to parse wallet address
2017/12/03 08:22:15 Error while refreshing block template: Failed to parse wallet address
2017/12/03 08:22:16 Error while refreshing block template: Failed to parse wallet address

Am I missing something?

**Comment by sammy007** [comment]
Maybe.

**Comment by StiiCeva** [comment]
Any hints?

**Comment by sammy007** [comment]
The hint is in your config but you refused to post it.

**Comment by StiiCeva** [comment]
Sorry @sammy007 ! You were right, the config was the problem. Thank you very much!

**Comment by travelbuzz** [comment]
How do I.compile Lib boost in ubuntu
