### ISSUE TITLE
json_rpc Error

### ISSUE THREAD

**Issue by godmonero** [sammy007/monero-stratum#84]
hello i started to use your pool and i have this error what means? or what i need for fix it?

2017/12/08 12:54:57 Error while refreshing block template: Post http://127.0.0.1:18081/json_rpc: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

I installed last Monero node, golang, etc etc 

Pool its running all good accepting shares etc but appears that error 

thanks

**Comment by sammy007** [comment]
What is timeout setting for this upstream?

**Comment by godmonero** [comment]
10 secs

**Comment by sammy007** [comment]
Something is wrong with daemon or system then, if you run it on same host there must be no timeout.

**Comment by godmonero** [comment]
Will that error cause a problem when finding a block?
What power do I need today to find blocks?

**Comment by sammy007** [comment]
A lot of power.
