### ISSUE TITLE
How to start stratum (detailed please)

### ISSUE THREAD

**Issue by vgalbur** [sammy007/monero-stratum#86]
Good day! I run all commands to install stratum
Now I don't understand how to start stratum??? I type ./build/bin/monero-stratum config.json but it write me -bash: ./build/bin/monero-stratum: No such file or directory . I edit config.json file with my address

**Comment by vgalbur** [comment]
when i type  root@vultr:~/monero/monero-stratum# ./config.json i receive the message:  
-bash: ./config.json: Permission denied

**Comment by sammy007** [comment]
https://github.com/sammy007/monero-stratum#running-stratum

**Comment by vgalbur** [comment]
But what can i type if  -bash: ./config.json: Permission denied

**Comment by sammy007** [comment]
I see you are trying to execute config file, so you didn't follow instructions.

**Comment by vgalbur** [comment]
Please help me, what file i need to execute? Thank You!

12 Дек 2017 г. 17:20 пользователь "Sammy Libre" <notifications@github.com>
написал:

**Comment by hidefog** [comment]
You need to execute the binary that you compiled.   Like @sammy007 said, read here; https://github.com/sammy007/monero-stratum#running-stratum It really is all laid out there.  You just need to read in infer the next steps based on your environment.

From what you are writing, I think this all might be a bit beyond your current skill set.  Get comfortable with working in a shell first, then move on to compiling and projects like this.

**Comment by sammy007** [comment]
```
make
./build/bin/monero-stratum config.json
```

**Comment by vgalbur** [comment]
Ok but what command i need to use? I follow all instruction step by step, i
configure file cofig.json and tle latest step is to run the server.i'm a
windows user i dont know all commands in Linux

12 Дек 2017 г. 5:40 PM пользователь "hidefog" <notifications@github.com>
написал:

**Comment by sammy007** [comment]
Please don't use it. You need a million dollar worth of hardware in order to find a block in a visible feature. Join public pool. Thread locked.
