### ISSUE TITLE
Error during build on Linux

### ISSUE THREAD

**Issue by avafe** [sammy007/monero-stratum#87]
I try do the same like in ReadMe.md
after clone stratum, make "cmake .", then write make and see this mistake
![123](https://user-images.githubusercontent.com/34391739/34057456-95fa2642-e209-11e7-9d8a-5d5a591c04c5.JPG)

It say could not found file or folder "cryptonote_basic/cryptonote_format_utils.h"
maybe some one know how to fix?

**Comment by sammy007** [comment]
Must follow README and set `MONERO_DIR` properly. Also build monero with special flags, then build this stratum.
