### ISSUE TITLE
Any ideas?

### ISSUE THREAD

**Issue by xstalpha** [sammy007/monero-stratum#88]
"make" command for Monero, after hanging for hours, this error:

[ 69%] Building CXX object src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o
cd /opt/src/monero/src/wallet && /usr/bin/c++   -DAUTO_INITIALIZE_EASYLOGGINGPP -DBLOCKCHAIN_DB=DB_LMDB -DBUILD_SHARED_LIBS -DDEFAULT_DB_TYPE=\"lmdb\" -DHAVE_READLINE -DPER_BLOCK_CHECKPOINT -DUPNP_DYNAMIC -I/opt/src/monero/external/easylogging++ -I/opt/src/monero/src -I/opt/src/monero/contrib/epee/include -I/opt/src/monero/external -I/opt/src/monero/version -I/usr/include/miniupnpc -I/opt/src/monero/external/db_drivers/liblmdb  -fno-strict-aliasing -maes -std=c++11 -D_GNU_SOURCE   -Wall -Wextra -Wpointer-arith -Wundef -Wvla -Wwrite-strings -Wno-error=extra -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-unused-variable -Wno-error=unused-variable -Wno-error=undef -Wno-error=uninitialized -Wlogical-op -Wno-error=maybe-uninitialized -Wno-reorder -Wno-missing-field-initializers -march=native  -fPIC -fno-strict-aliasing -DNDEBUG -Ofast    -o CMakeFiles/obj_wallet.dir/wallet2.cpp.o -c /opt/src/monero/src/wallet/wallet2.cpp
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/wallet/CMakeFiles/obj_wallet.dir/build.make:62: recipe for target 'src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o' failed
make[2]: *** [src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o] Error 4
make[2]: Leaving directory '/opt/src/monero'
CMakeFiles/Makefile2:1255: recipe for target 'src/wallet/CMakeFiles/obj_wallet.dir/all' failed
make[1]: *** [src/wallet/CMakeFiles/obj_wallet.dir/all] Error 2
make[1]: Leaving directory '/opt/src/monero'
Makefile:138: recipe for target 'all' failed

Will look over it again tomorrow sometime, hoping someone might have an idea in the meanwhile :D

**Comment by xstalpha** [comment]
May have been insufficient RAM... set up a swap file and gonna let it run overnight, let's see what comes up when I get back to it. 


BTW, sorry to be a pain, and I appreciate y'all

**Comment by sammy007** [comment]
> Any ideas?

No ideas.
